project:
  type: website
  output-dir: docs
  pre-render: build_references.R

website:
  title: "Owen Hale"
  description: "This site is about the scientist Owen Hale. It includes information about his ongoing research and scientific publications."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about_me.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact
    right: 
      - icon: google
        href: https://scholar.google.com/citations?user=gDywkyIAAAAJ&hl=en&oi=ao
      - icon: github
        href: https://github.com/owenfhale
      - icon: twitter
        href: https://twitter.com/owenmicro
      - icon: linkedin
        href: https://www.linkedin.com/in/owenhale/

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

