project:
  type: website
  output-dir: docs
  pre-render: build_references.R

website:
  title: "Owen Hale"
  
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about_me.qmd
      - href: research.qmd
        text: Research
      - publications.qmd
      - contact.qmd
    right: 
      - icon: google
        href: https://scholar.google.com/citations?user=gDywkyIAAAAJ&hl=en&oi=ao
      - icon: github
        href: https://github.com/owenfhale
      - icon: twitter
        href: https://twitter.com/owenmicro
      - icon: linkedin
        href: https://www.linkedin.com/in/owenhale/

format:
  html:
    theme: litera
    css: styles.css
    toc: true

editor: visual

